In [1]:
"""
@author: pho
"""
## Automatic debugger on exception raised
# %pdb on
%pdb off
%load_ext autoreload
%autoreload 2
import sys
import importlib
from pathlib import Path
from copy import deepcopy
from numba import jit
import numpy as np
import pandas as pd

%config Completer.use_jedi = False

# # required to enable non-blocking interaction:
%gui qt5

import os
import numpy as np
import pandas as pd
from pathlib import Path
import dill as pickle

from neuropy.utils.load_exported import LoadXml, find_session_xml # for compute_with_params_loaded_from_xml
from cnn_ripple.PhoRippleDetectionTesting import ExtendedRippleDetection, main_compute_with_params_loaded_from_xml

Automatic pdb calling has been turned OFF


In [2]:
local_session_parent_path = Path(r'W:\Data\KDIBA\gor01\one')
# local_session_parent_path = Path(r'/Volumes/MoverNew/data/KDIBA/gor01/one')
local_session_names_list = ['2006-6-07_11-26-53', '2006-6-08_14-26-15', '2006-6-09_1-22-43', '2006-6-09_3-23-37', '2006-6-12_15-55-31', '2006-6-13_14-42-6']
local_session_paths_list = [local_session_parent_path.joinpath(a_name).resolve() for a_name in local_session_names_list]

local_session_path: Path = local_session_paths_list[1]
local_session_path

WindowsPath('W:/Data/KDIBA/gor01/one/2006-6-08_14-26-15')

## Load previously computed result

In [3]:
loaded_ripple_detector = ExtendedRippleDetection.load(local_session_path)
loaded_ripple_detector

assuming the passed in directory is the active_local_session_path, building default in_ripple_detector_filepath from it...
	 in_ripple_detector_filepath: W:\Data\KDIBA\gor01\one\2006-6-08_14-26-15\ripple_detector.pkl
loading pickled ripple detector object from W:\Data\KDIBA\gor01\one\2006-6-08_14-26-15\ripple_detector.pkl...
done.


In [4]:
ripple_predictions_df = loaded_ripple_detector.continuous_ripple_likelihoods_df
prediction_timesteps = loaded_ripple_detector.continuous_ripple_prediction_timesteps
prediction_values = loaded_ripple_detector.continuous_ripple_shanks_prediction_values_array 
new_ripple_df = loaded_ripple_detector.detected_ripple_epochs_df

In [12]:
# ripple_predictions_df[ripple_predictions_df.columns[1:]]
[ripple_predictions_df[col].to_numpy() for col in ripple_predictions_df.columns[1:]]

[array([0.00774333, 0.00617211, 0.00344333, ..., 0.01510757, 0.02175885,
        0.00010243], dtype=float32),
 array([0.07346644, 0.05991831, 0.00566955, ..., 0.06015559, 0.05113016,
        0.00010243], dtype=float32),
 array([2.5703071e-02, 2.7096704e-01, 5.3490005e-02, ..., 6.1092828e-03,
        3.5859835e-03, 1.0242617e-04], dtype=float32),
 array([0.00010769, 0.00010837, 0.0001152 , ..., 0.00125491, 0.00063872,
        0.00010243], dtype=float32),
 array([0.00259279, 0.00061897, 0.00124454, ..., 0.00078206, 0.00451967,
        0.00010243], dtype=float32),
 array([0.01444975, 0.02094514, 0.03133143, ..., 0.04294315, 0.03892563,
        0.00010243], dtype=float32),
 array([0.00036104, 0.00046241, 0.00014877, ..., 0.00239831, 0.00345945,
        0.00010243], dtype=float32),
 array([2.2572530e-03, 2.8206338e-04, 7.8150675e-05, ..., 1.5606934e-02,
        7.0265718e-03, 1.0242617e-04], dtype=float32),
 array([1.5759157e-04, 5.6425353e-05, 1.7845446e-04, ..., 8.6930359e-04,
        3.8

In [6]:
loaded_ripple_detector.out_all_ripple_results

{'computation_params': {'overlapping': True,
  'window_size': 0.0128,
  'stride': 0.0064,
  'threshold': 0.7,
  'learning_rate': 0.001,
  'beta_1': 0.9,
  'beta_2': 0.999,
  'epsilon': 1e-07,
  'amsgrad': False},
 'results': {0: {'shank': 0,
   'channels': array([71, 72, 73, 74, 75, 76, 77, 78]),
   'time_windows': array([[[-3.57666016e-01,  3.67919922e-01,  4.84619141e-01, ...,
             2.79052734e-01, -6.91528320e-02, -1.49169922e-01],
           [-1.91284180e-01,  5.71777344e-01,  5.52734375e-01, ...,
            -1.34887695e-01, -3.89892578e-01, -3.42773438e-01],
           [-1.30859375e-01,  6.43554688e-01,  6.15234375e-01, ...,
             6.52694702e-03, -2.57324219e-01, -3.11523438e-01],
           ...,
           [-6.63085938e-01, -1.70410156e-01, -2.02270508e-01, ...,
            -1.65039062e-01, -4.34814453e-01, -3.52050781e-01],
           [-1.07910156e+00, -4.37500000e-01, -4.37011719e-01, ...,
            -6.19628906e-01, -9.80957031e-01, -7.50976562e-01],
          

In [5]:
loaded_ripple_detector.good_results

{0: {'shank': 0,
  'channels': array([71, 72, 73, 74, 75, 76, 77, 78]),
  'time_windows': array([[[-3.57666016e-01,  3.67919922e-01,  4.84619141e-01, ...,
            2.79052734e-01, -6.91528320e-02, -1.49169922e-01],
          [-1.91284180e-01,  5.71777344e-01,  5.52734375e-01, ...,
           -1.34887695e-01, -3.89892578e-01, -3.42773438e-01],
          [-1.30859375e-01,  6.43554688e-01,  6.15234375e-01, ...,
            6.52694702e-03, -2.57324219e-01, -3.11523438e-01],
          ...,
          [-6.63085938e-01, -1.70410156e-01, -2.02270508e-01, ...,
           -1.65039062e-01, -4.34814453e-01, -3.52050781e-01],
          [-1.07910156e+00, -4.37500000e-01, -4.37011719e-01, ...,
           -6.19628906e-01, -9.80957031e-01, -7.50976562e-01],
          [-1.12792969e+00, -2.98339844e-01, -4.26269531e-01, ...,
           -5.76660156e-01, -8.90136719e-01, -6.82617188e-01]],
  
         [[-7.34375000e-01,  2.50976562e-01,  3.10546875e-01, ...,
            4.36096191e-02, -3.54492188e-01, -

## Build and run completely new detector:

In [ ]:
session_xml_filepath, session_stem, local_session_path = find_session_xml(local_session_path)
out_xml_dict, d = LoadXml(session_xml_filepath)
active_shank_channels_lists = out_xml_dict['AnatGrps']
# active_shank_channels_lists = [active_shank_channels_lists[i] for i in [0,1,2]]
print(f"active_shank_channels_lists: {active_shank_channels_lists}")

In [ ]:
test_detector = ExtendedRippleDetection(learning_rate=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-07, amsgrad=False)
ripple_df, out_all_ripple_results = test_detector.compute(**({'active_session_folder': local_session_path,
     'numchannel': out_xml_dict['nChannels'], 'srLfp': out_xml_dict['lfpSampleRate'], 'active_shank_channels_lists': active_shank_channels_lists,
     'overlapping': True, 'window_size': 0.0128, 'window_stride': 0.0064}))

# out_all_ripple_results
ripple_df.to_pickle(local_session_path.joinpath('ripple_df.pkl'))
print(f'done. Exiting.')

test_detector.save()

# Result Visualization

In [ ]:
from cnn_ripple.visualizations.plot_ripples import plot_ripples

#@title Time (in seconds) { run: "auto", vertical-output: true, display-mode: "form" }
second =  0#@param {type:"integer"}

pred_indexes = loaded_ripple_detector.results[0]['pred_indexes'] # note only uses shank 0
fig, ax, plot_data = plot_ripples(loaded_ripple_detector.loaded_eeg_data, pred_indexes, second, downsampled_fs=1250)
# plot_data: {'lines':lines, 'fills':fills}

# Overflow

In [ ]:
## Update old pickled objects 2022-11-05:
loaded_ripple_detector._detected_ripple_epochs_df = ExtendedRippleDetection._build_post_load_ripple_df(loaded_ripple_detector.good_results.copy(), debug_print=False)
print(f'Saving ripple_df to csv: {loaded_ripple_detector.predicted_ripples_dataframe_csv_save_filepath}')
detected_ripple_epochs_df.to_csv(loaded_ripple_detector.predicted_ripples_dataframe_csv_save_filepath)
loaded_ripple_detector.save()

In [ ]:
def keys(a_dict, debug_print=True):
    out_list = list(a_dict.keys())
    if debug_print:
        print(out_list)
    return out_list

In [ ]:
test_detector, ripple_df, out_all_ripple_results, out_all_ripple_results = main_compute_with_params_loaded_from_xml(active_local_session_path)

In [ ]:
out_all_ripple_results['preprocessed_data']['data']

In [ ]:
out_all_ripple_results['computation_params']

In [ ]:
print(list(out_all_ripple_results['computation_params'].keys()))

In [ ]:
keys(out_all_ripple_results['computation_params'])
keys(out_all_ripple_results['preprocessed_data'])
keys(out_all_ripple_results['results'])

In [ ]:
from neuropy.utils.dynamic_container import DynamicContainer, override_dict, overriding_dict_with, get_dict_subset

# ['overlapping', 'window_size', 'stride', 'threshold', 'learning_rate', 'beta_1', 'beta_2', 'epsilon', 'amsgrad']
get_dict_subset(out_all_ripple_results['computation_params'], ['learning_rate', 'beta_1', 'beta_2', 'epsilon', 'amsgrad'])

In [ ]:
test_detector.save()

In [ ]:
loaded_ripple_detector.loaded_eeg_data

In [ ]:
keys(loaded_ripple_detector.results[0]['pred_indexes'])

## Batch resave previous pickles:

In [ ]:
for local_session_path in local_session_paths_list:
    in_ripple_detector_filepath = local_session_path.joinpath('ripple_detector.pkl')
    print(f'in_ripple_detector_filepath: {in_ripple_detector_filepath}')
    loaded_ripple_detector = ExtendedRippleDetection.load(in_ripple_detector_filepath)
    loaded_ripple_detector.save()